AllCops:
  NewCops: enable

# --- Personal preferences ---
Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic

# --- DragonRuby basic settings ---

# See this as refactoring suggestion not problem
Metrics/AbcSize:
  Severity: info

# See this as refactoring suggestion not problem
Metrics/MethodLength:
  Severity: info
  Exclude:
    - mygame/tests/**/*

# Not yet supported - Enable after updated to mruby 3.2
Naming/BlockForwarding:
  Enabled: false

# Typical parameters/attributes for DragonRuby primitives
Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - w
    - h
    - r
    - g
    - b
    - a

Style/Documentation:
  Exclude:
    - mygame/tests/**/*

# Meaningless in mruby
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - $gtk

# Not yet supported - Enable after updated to mruby 3.1
Style/HashSyntax:
  Enabled: false

# Not implemented in mruby
Style/RandomWithOffset:
  Enabled: false
