#!/bin/sh

set -e

cd $(dirname $0)/..

extension=$1

if [ -z $extension ]; then
  echo "Usage: $0 <extension>" >&2
  exit 1
fi

determine_ndk_platform() {
  if [ $(uname) = "Darwin" ]; then
    echo "darwin-x86_64"
  elif [ $(uname) = "Linux" ]; then
    echo "linux-x86_64"
  else
    echo "Unsupported platform: $(uname)" >&2
    exit 1
  fi
}

output_path="./mygame/native/googleplay-arm64"
mkdir -p $output_path

ndk_llvm_path="./android/ndk/26.3.11579264/toolchains/llvm/prebuilt/$(determine_ndk_platform)"
clang=$ndk_llvm_path/bin/aarch64-linux-android33-clang

$clang --sysroot=$ndk_llvm_path/sysroot \
       -shared \
       -Wl,-undefined -Wl,dynamic_lookup \
       -fPIC \
       -I ./include \
       ./app-native/$extension.c \
       -o $output_path/$extension.so
