#!/bin/sh

set -e

cd $(dirname $0)/..

keytool -genkeypair -v \
        -keystore ./android/keystore.jks \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -alias mygame
