#!/bin/sh

set -e

cd $(dirname $0)/..

keytool -genkeypair -v \
        -keystore ./android/dev_keystore.jks \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -alias mygame \
        -storepass mygame \
        -dname "CN=mygame, OU=mygame, O=mygame, L=mygame, S=mygame, C=us"
