#!/bin/sh

set -e

cd $(dirname $0)/..

path_to_cmdline_tools=$1

if [ -z "$path_to_cmdline_tools" ]; then
    echo "Usage: $0 path_to_cmdline_tools"
    exit 1
fi

log() {
  echo "[setup-build-environment] $1"
}

mkdir android

log "Copying cmdline-tools to android/cmdline-tools"
cp -r $path_to_cmdline_tools android/cmdline-tools

sdkmanager="./android/cmdline-tools/latest/bin/sdkmanager"

log "Accepting licenses"
yes | $sdkmanager --sdk_root=android --licenses > /dev/null

# Handling APKs and testing
log "Installing Platform Tools"
$sdkmanager --sdk_root=android --install 'platform-tools'

log "Installing bundletool"
curl -L -o android/bundletool.jar \
     https://github.com/google/bundletool/releases/download/1.17.2/bundletool-all-1.17.2.jar

# C Extensions
log "Installing NDK"
$sdkmanager --sdk_root=android --install 'ndk;26.3.11579264'

log "Installing Build Tools"
$sdkmanager --sdk_root=android --install 'build-tools;30.0.0'

log "Installing Platform SDK"
$sdkmanager --sdk_root=android --install 'platforms;android-34'
